version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: express-handlebars
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: nodemailer-mailgun-transport
    versions:
    - 2.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
